[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Patronus"
authors = [{name = "Akhil Mahendra", email = "akhilmahendra7991@gmail.com"}]
dynamic = ["version", "description"]
